### ISSUE TITLE
EBNF文法的优先级问题

### ISSUE THREAD

**Issue by noirgif** [ustc-compiler/2017fall#2]
在C语言中前缀操作符拥有比四则运算高的优先级。然而使用提供的EBNF文法，或者C1Parser.g4中的示例，前缀操作符`+`和`-`的优先级低于四则运算。比如
```c
int i = -1-1;
```
就会被分析成`int i = -(1-1);`与实际不符。
将 UnaryOp exp 提到 exp  BinOp exp 之前或许可以解决问题。

**Comment by Blealtan** [comment]
Bug证实存在。
2017fall仓库中的内容已经修复，文档也相应地做了修改。
