### ISSUE TITLE
EBNF文法中statement导出语法问题

### ISSUE THREAD

**Issue by noirgif** [ustc-compiler/2017fall#5]
在gitbook的EBNF文法中，statement和declaration是无关系的，statement不能导出declaration。这在lab1-1和lab1-2中没有影响。

但在lab1-3中`include/c1recognizer/syntax_tree.h`中，`class decl_syntax`继承`class stmt_syntax`。但在EBNF文法中没有体现。

这个变化尤其好处，因为这样block中的`ptr_list<stmt_syntax*> body`得以成立而不会出现类不兼容，也避免了statement 和 declaration分别在两个vector中，将其排序的麻烦。

因此对EBNF的更改建议是添加stmt -> decl.

**Comment by Blealtan** [comment]
这一继承关系的目的实际上在于避免为stmt_syntax和decl_syntax提供一个无意义的共同基类，这导致了syntax tree和EBNF的不一致，确实是实验设计的缺陷。可行的改进是你所提及的EBNF更改，或提供独立的block_item_syntax；但考虑到前者将涉及到lab1-2的结果修订，后者将涉及到重新分发实验框架代码，并且即使EBNF和syntax tree不一致也不影响实验的开展，这里暂时不进行改动，按照原框架继续实验。
