### ISSUE TITLE
var_def_stmt_syntax应保存一串变量定义

### ISSUE THREAD

**Issue by noirgif** [ustc-compiler/2017fall#6]
EBNF文法中常数和变量定义的规则为：
```
ConstDecl   → const int ConstDef { , ConstDef } ';'
VarDecl     → int Var { , Var } ';'
```

因此在对应的`struct var_def_stmt_syntax`中，应有一串变量定义而不是单个变量的定义。

可以对syntax_tree.h进行如下更改：

```cpp
struct var_def_stmt_syntax : stmt_syntax, global_def_syntax
{
    bool is_constant;
    std::vector<std::string> name;
    std::vector<ptr_list<expr_syntax>> array_length; // nullptr for non-array variables
    std::vector<ptr_list<expr_syntax>> initializers;
    virtual void accept(syntax_tree_visitor &visitor) override final;
};
```

或者维持`struct var_def_stmt_syntax`，增加对应列表的`struct list_var_def_stmt_syntax`，此时需要将`is_constant`转移到新的列表类中。不过这样的好处是保留了ConstDecl和ConstDef之间的阶级关系，使得syntax_tree_builder更加具有层次性。

**Comment by clarazhang** [comment]
没必要增加 `struct list_var_def_stmt_syntax` 啊, 不是有现成的list模板类吗

**Comment by noirgif** [comment]
使用std::vector可以（并非使用assembly

**Comment by Blealtan** [comment]
这里只用一阶list的原因是虽然一个语句中可以定义多个变量，但行为与多个语句每个语句定义单个变量是一致的，没有必要一定在一个stmt_syntax中表达多个定义，在其父节点中插入多个stmt_syntax即可。晚些时候我会发布reference版本的二进制程序`c1r_test`，各位可以参考它进行自己的代码编写。
