### ISSUE TITLE
数组长度未显式说明时的疑惑

### ISSUE THREAD

**Issue by FloridSleeves** [ustc-compiler/2017fall#7]
数组长度没有显式表示出来的时候，如：
int a[]={1,2,3};
此时array_length中的成员line,pos应该是什么。

**Comment by noirgif** [comment]
助教给的程序里没有初始化line和pos

**Comment by Blealtan** [comment]
十分抱歉，这是我的疏忽。修正后的二进制程序已经在群文件中更新。
