### ISSUE TITLE
示例程序std::bad_cast

### ISSUE THREAD

**Issue by FloridSleeves** [ustc-compiler/2017fall#8]
当用示例二进制程序运行附件中的test2.txt
`./c1r_test test2.txt`
时，出现错误
```
terminate called after throwing an instance of 'std::bad_cast'
  what():  std::bad_cast
已放弃 (核心已转储)
```
[test2.txt](https://github.com/ustc-compiler/2017fall/files/1405031/test2.txt)

**Comment by Blealtan** [comment]
示例二进制已更新。问题在于empty_stmt_syntax的处理，已经修复。
